INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (1, 'XRA', 1, 'Xray Event', 'P1', '1-8A');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (2, 'FLA', 10, 'Halpha Flare', 'P1', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (3, 'BSL', 20, 'Bright Surge on the limb', 'BSL', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (4, 'DSF', 21, 'Disappearing Solar Filament', 'DSF', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (5, 'EPL', 22, 'Eruptive Prominence on Limb', 'EPL', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (6, 'LPS', 23, 'Loop Prominence System', 'LPS', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (7, 'SPY', 24, 'Spray', 'SPY', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (8, 'UFILA', 25, 'Disappearing Filament (ISES)', 'DSF', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (9, 'DSD', 29, 'Dark Surge on the Disk', 'DSD', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (10, 'RBR', 30, '<150 MHz Radio Burst', '150', '<150');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (11, 'RBR', 31, '245 MHz Radio Burst', '245', '245');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (12, 'RBR', 32, '410 MHz Radio Burst', '410', '410');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (13, 'RBR', 33, '606/610 MHz Radio Burst', '610', '606');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (14, 'RBR', 34, '1415 MHz Radio Burst', '1415', '1415');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (15, 'RBR', 35, '2695 MHz Radio Burst', '2695', '2695');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (16, 'RBR', 36, '4995 MHz Radio Burst', '4995', '4995');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (17, 'RBR', 37, '8800 MHz Radio Burst', '8800', '8800');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (18, 'RBR', 38, '15400 MHz Radio Burst', '15400', '15400');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (19, 'RBR', 39, '>20000 MHz Radio Burst', '20000', '>=2000');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (20, 'RNS', 41, '204/245 MHz Radio Noise Storm', 'P1', '245');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (21, 'RNS', 42, '410 MHz Radio Noise Storm', '410 RNS', '410');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (22, 'RNS', 43, '606/610 MHz Radio Noise Storm', '610 RNS', '606');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (23, 'RNS', 44, '1415 MHz Radio Noise Storm', '1415 RNS', '1415');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (24, 'RNS', 45, '2695 MHz Radio Noise Storm', '2695 RNS', '2695');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (25, 'RNS', 46, '4995 MHz Radio Noise Storm', '4995 RNS', '4995');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (26, 'RNS', 47, '8800 MHz Radio Noise Storm', '8800 RNS', '8800');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (27, 'RNS', 48, '15400 MHz Radio Noise Storm', '15400 RNS', '15400');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (28, 'RNS', 49, '>20000 MHz Radio Noise Storm', '20000 RNS', '>=20000');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (29, 'RSP', 50, 'TypeII Radio Sweep', 'II', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (30, 'RSP', 51, 'TypeIII Radio Sweep', 'III', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (31, 'RSP', 52, 'TypeIV Radio Sweep', 'IV', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (32, 'RSP', 53, 'TypeV Radio Sweep', 'V', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (33, 'RSP', 54, 'CTM Sweep', 'CTM', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (34, 'RSP', 55, 'TypeVI Sweeps', 'VI', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (35, 'RSP', 56, 'TypeVII Sweeps', 'VII', '30-80');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (36, 'CME', 98, 'SWPC Coronal Mass Ejection', 'CME', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (37, 'UCMEO', 99, 'NASA Coronal Mass Ejection', 'CME', '');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (38, 'PRO', 60, '10Mev Proton Event', 'PRO', '10Mev');
INSERT INTO awips.swpc_event_type (id, type, code, description, indicator, frequency) VALUES (39, 'PRO', 61, 'Other Frequency Proton Event', 'PRO', '');

